services:
  # The AI Engine
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - HOME=/home/ubuntu
    volumes:
      - ollama-data:/home/ubuntu/.ollama
      - ./ollama_setup.sh:/ollama_setup.sh
    entrypoint: ["/usr/bin/bash", "/ollama_setup.sh"]
    ports:
      - "11434:11434"

  # The FastAPI Backend
  backend:
    build: ./backend
    container_name: aromin_ai-backend
    env_file:
      - ./.env
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data

  frontend:
    build: ./frontend
    container_name: aromin_ai-frontend
    env_file:
      - ./.env
    ports:
      - "3000:8080"
    depends_on:
      - backend

volumes:
  ollama-data:
  backend-data:
