services:
  # The AI Engine
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

  # The FastAPI Backend
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./.env
    # environment:
    #   OLLAMA_HOST: ${OLLAMA_HOST}
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data

  frontend:
    build: ./frontend
    container_name: frontend
    # environment:
    #   VITE_API_URL: ${VITE_API_URL}
    env_file:
      - ./.env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ollama-data:
  backend-data:
